export const paths = {
  login: "/login",
  promo: "promo",
  home: "/",

  reg_event: "/",
  submit_job: "/",
  registration: "registration",
  steps: "steps",
  nominations: "nominations",
  participants: "participants",
  price: "price",
  requirements: "requirements",
  criteria: "criteria",
  jury_main: "jury_main",
  jury_special: "jury_special",
  program: "program",
  speakers: "speakers",
  festival: "about_the_festival",
  faq: "faq",
  contacts: "contacts",
  pitch: "pitch",
  partners: "partners",
  private: "profile",
  young_talent: "young_talent",
  pass: "pass",

  profile: "profile",
  recovery: "recovery",
};
