export const paths = {
  login: "/login",
  reg_event: "/",
  submit_job: "/",
  registration: "registration",
  steps: "steps",
  nominations: "nominations",
  submission_of_works: "submission_of_works",
  price: "price",
  requirements: "requirements",
  criteria: "criteria",
  jury: "jury",
  program: "program",
  speakers: "speakers",
  festival: "about_the_festival",
  faq: "faq",
  contacts: "contacts",

  private: "private",
};
